#ifndef PROJECTTREEVIEWDELETESELECTIONCOMMAND_H
#define PROJECTTREEVIEWDELETESELECTIONCOMMAND_H


class ProjectTreeViewDeleteSelectionCommand
{
public:
  ProjectTreeViewDeleteSelectionCommand();
};

#endif // PROJECTTREEVIEWDELETESELECTIONCOMMAND_H
