/*************************************************************************************************************
 Copyright (c) 2006-2019 David Dubbeldam, Sofia Calero, Thijs J.H. Vlugt.

    D.Dubbeldam@uva.nl            http://www.acmm.nl/molsim/users/dubbeldam/index.html
    scaldia@upo.es                http://www.upo.es/raspa/sofiacalero.php
    t.j.h.vlugt@tudelft.nl        http://homepage.tudelft.nl/v9k6y

 Permission is hereby granted, free of charge, to any person
 obtaining a copy of this software and associated documentation
 files (the "Software"), to deal in the Software without
 restriction, including without limitation the rights to use,
 copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the
 Software is furnished to do so, subject to the following
 conditions:

 The above copyright notice and this permission notice shall be
 included in all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
 OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
 HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
 WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 OTHER DEALINGS IN THE SOFTWARE.
 *************************************************************************************************************/

#include <cmath>
#include <qmath.h>
#include "skelement.h"
#include "skpdbwriter.h"

SKPDBWriter::SKPDBWriter(QString displayName, SKSpaceGroup &spacegroup, std::shared_ptr<SKCell> cell, double3 origin, std::vector<std::shared_ptr<SKAsymmetricAtom>> atoms):
   _displayName(displayName), _spacegroup(spacegroup), _cell(cell), _origin(origin), _atoms(atoms)
{
}

QString SKPDBWriter::string()
{
  QString outputString = "COMPND    " + _displayName + "\n" + "AUTHOR    GENERATED BY IRASPA\n";

  if(_cell)
  {
    QString spaceGroupRecordName = "CRYST1";
    QString a = QString("%1").arg(_cell->a(), 9, 'f', 3, ' ');
    QString b = QString("%1").arg(_cell->b(), 9, 'f', 3, ' ');
    QString c = QString("%1").arg(_cell->c(), 9, 'f', 3, ' ');
    QString alpha = QString("%1").arg(_cell->alpha() * 180.0 / M_PI, 7, 'f', 2, ' ');
    QString beta = QString("%1").arg(_cell->beta() * 180.0 / M_PI, 7, 'f', 2, ' ');
    QString gamma = QString("%1").arg(_cell->gamma() * 180.0 / M_PI, 7, 'f', 2, ' ');

    QString spaceGroupString = _spacegroup.spaceGroupSetting().HMString().leftJustified(11, ' ', true);
    QString zValue = QString("%1").arg(_cell->zValue()).rightJustified(4, ' ', true);

    QString line = spaceGroupRecordName + a + b + c + alpha + beta + gamma + " " + spaceGroupString + zValue + "\n";
    outputString += line;
  }

  int counter = 1;
  for(std::shared_ptr<SKAsymmetricAtom> atom : _atoms)
  {
    int atomicNumber = atom->elementIdentifier();
    SKElement element = PredefinedElements::predefinedElements[atomicNumber];
    QString elementSymbol =  element._chemicalSymbol.rightJustified(2, ' ', true);
    QString atomRecordName = "ATOM  ";
    QString atomSerialNumber = QString::number(counter).rightJustified(5, ' ', true);
    QString atomName = elementSymbol;
    QString remotenessIndicator = QString(atom->remotenessIndicator());
    QString branchIndicator = QString(atom->branchDesignator());
    QString alternateLocationIndicator = QString(" ");
    QString residueName = atom->residueName().rightJustified(3, ' ', true);
    QString chainIdentifier = QString(atom->chainIdentifier());
    QString residueSequenceNumber = QString::number(atom->residueSequenceNumber()).rightJustified(4, ' ', true);
    QString codeForInsertionOfResidues = QString(atom->codeForInsertionOfResidues());
    QString orthogonalCoordinatesForX =  QString("%1").arg(atom->position().x - _origin.x, 8, 'f', 3, ' ');
    QString orthogonalCoordinatesForY =  QString("%1").arg(atom->position().y - _origin.y, 8, 'f', 3, ' ');
    QString orthogonalCoordinatesForZ =  QString("%1").arg(atom->position().z - _origin.z, 8, 'f', 3, ' ');
    QString occupancy =  QString("%1").arg(atom->occupancy(), 6, 'f', 2, ' ');
    QString isotropicBFactor =  QString("%1").arg(atom->temperaturefactor(), 6, 'f', 2, ' ');
    QString segmentIdentifier = atom->segmentIdentifier().rightJustified(4, ' ', true);
    QString charge = QString("  ");
    QString line = atomRecordName + atomSerialNumber + " " + atomName + remotenessIndicator + branchIndicator +
                   alternateLocationIndicator + residueName + " " + chainIdentifier + residueSequenceNumber +
                   codeForInsertionOfResidues + "   " + orthogonalCoordinatesForX + orthogonalCoordinatesForY +
                   orthogonalCoordinatesForZ + occupancy + isotropicBFactor + "      " +
                   segmentIdentifier + elementSymbol + charge + "\n";
    outputString += line;
    counter += 1;
  }

  outputString += "END\n";

  return outputString;
}
