name: iraspa
version: 1.1.15
summary: A molecular visualizer/editor
icon: iRASPA/iraspa.png
description: |
  iRASPA is a visualization package (with editing capabilities) aimed at 
  material science. Examples of materials are metals, metal-oxides, ceramics,
  biomaterials, zeolites, clays, and metal-organic frameworks. iRASPA leverages
  the latest visualization technologies with stunning performance. It can 
  handle large structures (hundreds of thousands of atoms), including ambient 
  occlusion, with high frame rates.
grade : stable
confinement: strict

apps:
  iraspa:
    command: desktop-launch $SNAP/usr/bin/iraspa
    desktop: usr/share/applications/iraspa.desktop
    plugs: [unity7, x11, home, opengl, network, browser-support, desktop ]

parts:
  iraspa:
    source: .
    plugin: qmake
    qt-version: qt5
    project-files: [ iRASPA.pro]
    override-build: |
      snapcraftctl build
      install -D iraspa $SNAPCRAFT_PART_INSTALL/usr/bin
    options: ["CONFIG+=release", "QMAKE_CXX=clang++-6.0", "DEFINES += USE_SNAP"]
    build-packages: [llvm-6.0, clang-6.0, build-essential, cmake, dbus, qtdeclarative5-dev-tools, qt5-default, qtbase5-dev, liblzma-dev, libz-dev, libqt5webkit5-dev, ocl-icd-opencl-dev, libpython2.7-dev, zlib1g-dev]
    stage-packages: [libqt5gui5, libqt5core5a, libqt5printsupport5, libqt5qml5, libqt5quick5, libqt5webkit5, libqt5opengl5, ocl-icd-libopencl1, libpython2.7]
    after: [qt5conf, desktop-qt5]
  iraspa-copy-files:
    plugin: dump
    source: iRASPA
    organize:
      iraspa.png: usr/share/pixmaps/iraspa.png
      iraspa.desktop: usr/share/applications/iraspa.desktop
      AcknowledgedLicenses.pdf: usr/share/iraspa/AcknowledgedLicenses.pdf
      LibraryOfStructures.irspdoc: usr/share/iraspa/LibraryOfStructures.irspdoc

